### PR TITLE
Changed Tahoma enduserAPI

### PR DESCRIPTION
**Pull request by jeroenvanderschoot**

### CODE REVIEW

**Comment by gieljnssns** [comment]
@philklei 
did you see this?
https://github.com/philklei/tahoma-api/issues/16#issuecomment-563301633

**Comment by butako** [comment]
I just want to add, I have tested this with my HA, Velux blinds/windows, and it's working great. 
Thank you for the quick work!

**Comment by tetienne** [comment]
You will have to revert my PR: https://github.com/home-assistant/home-assistant/pull/29745 and do the same for the documentation.

**Comment by dennismeng** [comment]
How do one install and test this?

**Comment by alex7614** [comment]
Hi

Yes I’m also interested to install in HassOS if it’s possible while waiting for an official patch to make it works again

Thanks

**Comment by alex7614** [comment]
Ok I tested and it works fine !

Thanks for all.

I crated a custom component folder with tahoma module from git and edit the file manifest.json with the new version 0.0.16 instead of 0.0.14 of tahoma_api

**Comment by dennismeng** [comment]
Where can this custom component folder be downloaded from? I'd like to test it as well.

**Comment by alex7614** [comment]
I just downloaded 7 files from : https://github.com/home-assistant/home-assistant/tree/master/homeassistant/components/tahoma

And I transferred the files to a folder I created called: tahoma in /config/custom_components

After I edited the file manifest.json and I replaced :    "tahoma-api==0.0.14"  to  "tahoma-api==0.0.16"

After a host reboot, Home Assistant downloaded the new version of the tahoma-api dependency and this has re-worked for me.

**Comment by dennismeng** [comment]
Ok will try to do the same, thanks for input - will provide feedback when tested :)

**Comment by dennismeng** [comment]
It works!
Wonder for how long this is going to continue to work .... anyone have any ideas? 
Such a shame their official API doesn't support a low of things :-(

**Comment by nyroDev** [comment]
> It works!
> Wonder for how long this is going to continue to work .... anyone have any ideas?
> Such a shame their official API doesn't support a low of things :-(

As far as I can see, the API used is the exact same API used on the website, when you're logged in here https://www.tahomalink.com/enduser-mobile-web/steer-html5-client/tahoma/

The code here simply mock up request that your browser do when you're using this website, in the exact same way.

So this will work until they decide to update their website, which means they will have to rewrite almost every source code of it...

**Comment by dennismeng** [comment]
Ok that's pretty great!
Will it be part of a coming HA release or should we run custom from now on?

**Comment by ghost** [comment]
For me it is still no working... still generate error.

**Pull request merged**
